name: Test Build

on:
  pull_request:
    branches: [terrain3d]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install and Build ğŸ”§
        run: |
          cd style
          npm install --include=dev
          sed 's/<your MapTiler key>/get_your_own_OpIi9ZULNHzrESv6T2vL/g' configs/config.maptiler.js > config.js
          npm run build
        # MapTiler key get_your_own_OpIi9ZULNHzrESv6T2vL is the MapLibre demo key
